### ISSUE TITLE
add any data structures and algorithms in c++

### ISSUE THREAD

**Issue by prydt** [PryDt/algorithms-cpp#1]

**Comment by yatind01** [comment]
what kind of data structures or algorithms do you want?

**Comment by rattandeep1998** [comment]
Added bubble sort. @PryDt

**Comment by AkshGautam** [comment]
Can i work on Trie/merge sort in cpp?mention if anything else is needed

**Comment by tushgup** [comment]
Added quick sort! @PryDt

**Comment by AKKamath** [comment]
#5 Added heap sort

**Comment by AkshGautam** [comment]
added fenwick tree #6

**Comment by AkshGautam** [comment]
added Bellman ford please review PRs

**Comment by prydt** [comment]
reviewed all PRs... 😄 thanks for contributing!
