### ISSUE TITLE
Update README.md with a list the contents of this repo

### ISSUE THREAD

**Issue by prydt** [PryDt/algorithms-cpp#9]
As this repo has grown, I haven't kept the README updated. (This should be an easy Hacktoberfest PR.) Just update the README.md with a complete list of all data structures and algorithms implemented in this repo.

**Comment by saurabhchalke** [comment]
Can I take this up?

**Comment by dhavdc** [comment]
I can do this.

**Comment by saurabhchalke** [comment]
Updated the README.md files as per the repo #12

**Comment by prydt** [comment]
Done and Merged, :smile: thanks for contributing!
